# Controls when the workflow will run
name: Main Workflow
on:
  push:
    branches:
    - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_job:
    name: build
    # runtime on which the job will be run
    runs-on: ubuntu-22.04 
    container: gradle:6-jdk11
    
    steps:
      - name: Clone
        uses: actions/checkout@v4  

      - name: Build
        run: ci/build-app.sh
      
      - name: Test
        run: ci/unit-test-app.sh

# TODO::
# Build and test: Clones down and run the gradle build command found in ci/build-app.sh, and thereafter runs the gradle test command found in ci/unit-test-app.sh
# Build docker: runs both building of the docker image, and pushes it up to the hub
# Component test: runs a docker-compose file with a python test to test the application.
# Performance test: runs a docker-compose file with a k6 performance tester to test the application.
