name: Version Compatibility
on:
  push:
    branches:
      - main

jobs:

  Build:
    runs-on: ubuntu-22.04 
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ["gradle:6-jdk8", "gradle:6-jdk11", "gradle:6-jdk17"]

    steps:
      - name: Clone
        uses: actions/checkout@v4  
        with:
          fetch-depth: 0
      
      - name: Test
        run: ci/unit-test-app.sh
      
      - name: Build
        run: ci/build-app.sh
  